package com.github.alexthe666.alexsmobs.misc;

import com.github.alexthe666.alexsmobs.AlexsMobs;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;

public class AMSoundRegistry {

    private static ResourceLocation id(String path) {
        return ResourceLocation.fromNamespaceAndPath(AlexsMobs.MODID, path);
    }

    private static SoundEvent register(String name) {
        return Registry.register(BuiltInRegistries.SOUND_EVENT, id(name), SoundEvent.createVariableRangeEvent(id(name)));
    }

    public static SoundEvent GRIZZLY_BEAR_IDLE;
    public static SoundEvent GRIZZLY_BEAR_HURT;
    public static SoundEvent GRIZZLY_BEAR_DIE;
    public static SoundEvent BEAR_DUST;

    public static SoundEvent ROADRUNNER_IDLE;
    public static SoundEvent ROADRUNNER_HURT;
    public static SoundEvent ROADRUNNER_MEEP;
    public static SoundEvent GAZELLE_HURT;
    public static SoundEvent CROCODILE_IDLE;
    public static SoundEvent CROCODILE_HURT;
    public static SoundEvent CROCODILE_BITE;
    public static SoundEvent CROCODILE_BABY;
    public static SoundEvent FLY_IDLE;
    public static SoundEvent FLY_HURT;
    public static SoundEvent HUMMINGBIRD_IDLE;
    public static SoundEvent HUMMINGBIRD_HURT;
    public static SoundEvent HUMMINGBIRD_LOOP;
    public static SoundEvent ORCA_IDLE;
    public static SoundEvent ORCA_HURT;
    public static SoundEvent ORCA_DIE;
    public static SoundEvent GORILLA_IDLE;
    public static SoundEvent GORILLA_HURT;
    public static SoundEvent MOSQUITO_LOOP;
    public static SoundEvent MOSQUITO_HURT;
    public static SoundEvent MOSQUITO_DIE;
    public static SoundEvent RATTLESNAKE_LOOP;
    public static SoundEvent RATTLESNAKE_HURT;
    public static SoundEvent RATTLESNAKE_ATTACK;
    public static SoundEvent ENDERGRADE_IDLE;
    public static SoundEvent ENDERGRADE_HURT;
    public static SoundEvent LOBSTER_HURT;
    public static SoundEvent LOBSTER_ATTACK;
    public static SoundEvent KOMODO_DRAGON_IDLE;
    public static SoundEvent KOMODO_DRAGON_HURT;
    public static SoundEvent SUNBIRD_IDLE;
    public static SoundEvent SUNBIRD_HURT;
    public static SoundEvent CAPUCHIN_MONKEY_IDLE;
    public static SoundEvent CAPUCHIN_MONKEY_HURT;
    public static SoundEvent BONE_SERPENT_IDLE;
    public static SoundEvent BONE_SERPENT_HURT;
    public static SoundEvent CENTIPEDE_WALK;
    public static SoundEvent CENTIPEDE_HURT;
    public static SoundEvent CENTIPEDE_ATTACK;
    public static SoundEvent WARPED_TOAD_IDLE;
    public static SoundEvent WARPED_TOAD_HURT;
    public static SoundEvent MOOSE_IDLE;
    public static SoundEvent MOOSE_HURT;
    public static SoundEvent MOOSE_JOSTLE;
    public static SoundEvent MIMICUBE_JUMP;
    public static SoundEvent MIMICUBE_HURT;
    public static SoundEvent RACCOON_IDLE;
    public static SoundEvent RACCOON_HURT;
    public static SoundEvent MARACA;
    public static SoundEvent LA_CUCARACHA;
    public static SoundEvent SEAL_IDLE;
    public static SoundEvent SEAL_HURT;
    public static SoundEvent COCKROACH_HURT;
    public static SoundEvent SHOEBILL_HURT;
    public static SoundEvent ELEPHANT_IDLE;
    public static SoundEvent ELEPHANT_HURT;
    public static SoundEvent ELEPHANT_DIE;
    public static SoundEvent ELEPHANT_TRUMPET;
    public static SoundEvent ELEPHANT_WALK;
    public static SoundEvent SOUL_VULTURE_IDLE;
    public static SoundEvent SOUL_VULTURE_HURT;
    public static SoundEvent SNOW_LEOPARD_IDLE;
    public static SoundEvent SNOW_LEOPARD_HURT;
    public static SoundEvent SPECTRE_IDLE;
    public static SoundEvent SPECTRE_HURT;
    public static SoundEvent CROW_IDLE;
    public static SoundEvent CROW_HURT;
    public static SoundEvent ALLIGATOR_SNAPPING_TURTLE_IDLE;
    public static SoundEvent ALLIGATOR_SNAPPING_TURTLE_HURT;
    public static SoundEvent MUNGUS_IDLE;
    public static SoundEvent MUNGUS_HURT;
    public static SoundEvent MUNGUS_LASER_END;
    public static SoundEvent MUNGUS_LASER_LOOP;
    public static SoundEvent MUNGUS_LASER_GROW;
    public static SoundEvent MANTIS_SHRIMP_SNAP;
    public static SoundEvent MANTIS_SHRIMP_HURT;
    public static SoundEvent GUSTER_IDLE;
    public static SoundEvent GUSTER_HURT;
    public static SoundEvent WARPED_MOSCO_IDLE;
    public static SoundEvent WARPED_MOSCO_HURT;
    public static SoundEvent STRADDLER_IDLE;
    public static SoundEvent STRADDLER_HURT;
    public static SoundEvent EMU_IDLE;
    public static SoundEvent EMU_HURT;
    public static SoundEvent PLATYPUS_IDLE;
    public static SoundEvent PLATYPUS_HURT;
    public static SoundEvent DROPBEAR_IDLE;
    public static SoundEvent DROPBEAR_HURT;
    public static SoundEvent TASMANIAN_DEVIL_IDLE;
    public static SoundEvent TASMANIAN_DEVIL_HURT;
    public static SoundEvent TASMANIAN_DEVIL_ROAR;
    public static SoundEvent KANGAROO_IDLE;
    public static SoundEvent KANGAROO_HURT;
    public static SoundEvent CACHALOT_WHALE_IDLE;
    public static SoundEvent CACHALOT_WHALE_HURT;
    public static SoundEvent CACHALOT_WHALE_CLICK;
    public static SoundEvent LEAFCUTTER_ANT_HURT;
    public static SoundEvent LEAFCUTTER_ANT_QUEEN_HURT;
    public static SoundEvent ENDERIOPHAGE_HURT;
    public static SoundEvent ENDERIOPHAGE_SQUISH;
    public static SoundEvent ENDERIOPHAGE_WALK;
    public static SoundEvent MUSIC_DISC_THIME;
    public static SoundEvent BALD_EAGLE_IDLE;
    public static SoundEvent BALD_EAGLE_HURT;
    public static SoundEvent TIGER_IDLE;
    public static SoundEvent TIGER_HURT;
    public static SoundEvent TIGER_ANGRY;
    public static SoundEvent TARANTULA_HAWK_WING;
    public static SoundEvent TARANTULA_HAWK_HURT;
    public static SoundEvent MUSIC_WORMBOSS;
    public static SoundEvent VOID_WORM_IDLE;
    public static SoundEvent VOID_WORM_HURT;
    public static SoundEvent VOID_PORTAL_CLOSE;
    public static SoundEvent VOID_PORTAL_OPEN;
    public static SoundEvent MIMIC_OCTOPUS_IDLE;
    public static SoundEvent MIMIC_OCTOPUS_HURT;
    public static SoundEvent MUSIC_DISC_DAZE;
    public static SoundEvent SEAGULL_IDLE;
    public static SoundEvent SEAGULL_HURT;
    public static SoundEvent FROSTSTALKER_IDLE;
    public static SoundEvent FROSTSTALKER_HURT;
    public static SoundEvent TUSKLIN_IDLE;
    public static SoundEvent TUSKLIN_HURT;
    public static SoundEvent LAVIATHAN_IDLE;
    public static SoundEvent LAVIATHAN_HURT;
    public static SoundEvent COSMAW_IDLE;
    public static SoundEvent COSMAW_HURT;
    public static SoundEvent TOUCAN_IDLE;
    public static SoundEvent TOUCAN_HURT;
    public static SoundEvent MANED_WOLF_IDLE;
    public static SoundEvent MANED_WOLF_HURT;
    public static SoundEvent ANACONDA_SLITHER;
    public static SoundEvent ANACONDA_HURT;
    public static SoundEvent ANACONDA_ATTACK;
    public static SoundEvent VINE_LASSO;
    public static SoundEvent ANTEATER_HURT;
    public static SoundEvent ROCKY_ROLLER_IDLE;
    public static SoundEvent ROCKY_ROLLER_HURT;
    public static SoundEvent ROCKY_ROLLER_EARTHQUAKE;
    public static SoundEvent GELADA_MONKEY_IDLE;
    public static SoundEvent GELADA_MONKEY_HURT;
    public static SoundEvent FLUTTER_IDLE;
    public static SoundEvent FLUTTER_HURT;
    public static SoundEvent FLUTTER_FLAP;
    public static SoundEvent FLUTTER_NO;
    public static SoundEvent FLUTTER_YES;
    public static SoundEvent JERBOA_IDLE;
    public static SoundEvent JERBOA_HURT;
    public static SoundEvent TERRAPIN_HURT;
    public static SoundEvent COMB_JELLY_HURT;
    public static SoundEvent COSMIC_COD_HURT;
    public static SoundEvent MOSQUITO_CAPSID_CONVERT;
    public static SoundEvent GIANT_SQUID_GAMES;
    public static SoundEvent APRIL_FOOLS_SCREAM;
    public static SoundEvent APRIL_FOOLS_POWER_OUTAGE;
    public static SoundEvent APRIL_FOOLS_MUSIC_BOX;
    public static SoundEvent BUNFUNGUS_IDLE;
    public static SoundEvent BUNFUNGUS_HURT;
    public static SoundEvent BUNFUNGUS_ATTACK;
    public static SoundEvent BUNFUNGUS_JUMP;
    public static SoundEvent BISON_IDLE;
    public static SoundEvent BISON_HURT;
    public static SoundEvent GIANT_SQUID_HURT;
    public static SoundEvent GIANT_SQUID_TENTACLE;
    public static SoundEvent DEVILS_HOLE_PUPFISH_HURT;
    public static SoundEvent SKELEWAG_HURT;
    public static SoundEvent SKELEWAG_IDLE;
    public static SoundEvent RAIN_FROG_HURT;
    public static SoundEvent RAIN_FROG_IDLE;
    public static SoundEvent POTOO_HURT;
    public static SoundEvent POTOO_CALL;
    public static SoundEvent MUDSKIPPER_HURT;
    public static SoundEvent MUDSKIPPER_WALK;
    public static SoundEvent MUDSKIPPER_SPIT;
    public static SoundEvent RHINOCEROS_IDLE;
    public static SoundEvent RHINOCEROS_HURT;
    public static SoundEvent SUGAR_GLIDER_IDLE;
    public static SoundEvent SUGAR_GLIDER_HURT;
    public static SoundEvent FARSEER_HURT;
    public static SoundEvent FARSEER_IDLE;
    public static SoundEvent FARSEER_EMERGE;
    public static SoundEvent FARSEER_BEAM;
    public static SoundEvent TRANSMUTE_ITEM;
    public static SoundEvent SKREECHER_HURT;
    public static SoundEvent SKREECHER_CALL;
    public static SoundEvent SKREECHER_DETECT;
    public static SoundEvent SKREECHER_CLAP;
    public static SoundEvent SCULK_BOOMER;
    public static SoundEvent SCULK_BOOMER_FART;
    public static SoundEvent UNDERMINER_IDLE;
    public static SoundEvent UNDERMINER_HURT;
    public static SoundEvent UNDERMINER_STEP;
    public static SoundEvent MURMUR_HURT;
    public static SoundEvent MURMUR_IDLE;
    public static SoundEvent MURMUR_NECK;
    public static SoundEvent MURMUR_ATTACK;
    public static SoundEvent MURMUR_ANGER;
    public static SoundEvent TENDON_WHIP;
    public static SoundEvent SKUNK_HURT;
    public static SoundEvent SKUNK_IDLE;
    public static SoundEvent SKUNK_SPRAY;
    public static SoundEvent STINK_RAY;
    public static SoundEvent BANANA_SLUG_HURT;
    public static SoundEvent BANANA_SLUG_SLIME_EXPAND;
    public static SoundEvent BLUE_JAY_IDLE;
    public static SoundEvent BLUE_JAY_HURT;
    public static SoundEvent BLUE_JAY_SONG;
    public static SoundEvent CAIMAN_IDLE;
    public static SoundEvent CAIMAN_HURT;
    public static SoundEvent CAIMAN_SPLASH;
    public static SoundEvent TRIOPS_HURT;
    public static SoundEvent END_PIRATE_DOOR;

    public static void init() {
        GRIZZLY_BEAR_IDLE = register("grizzly_bear_idle");
        GRIZZLY_BEAR_HURT = register("grizzly_bear_hurt");
        GRIZZLY_BEAR_DIE = register("grizzly_bear_die");
        BEAR_DUST = register("bear_dust");
        ROADRUNNER_IDLE = register("roadrunner_idle");
        ROADRUNNER_HURT = register("roadrunner_hurt");
        ROADRUNNER_MEEP = register("roadrunner_meep");
        GAZELLE_HURT = register("gazelle_hurt");
        CROCODILE_IDLE = register("crocodile_idle");
        CROCODILE_HURT = register("crocodile_hurt");
        CROCODILE_BITE = register("crocodile_bite");
        CROCODILE_BABY = register("crocodile_baby");
        FLY_IDLE = register("fly_idle");
        FLY_HURT = register("fly_hurt");
        HUMMINGBIRD_IDLE = register("hummingbird_idle");
        HUMMINGBIRD_HURT = register("hummingbird_hurt");
        HUMMINGBIRD_LOOP = register("hummingbird_loop");
        ORCA_IDLE = register("orca_idle");
        ORCA_HURT = register("orca_hurt");
        ORCA_DIE = register("orca_die");
        GORILLA_IDLE = register("gorilla_idle");
        GORILLA_HURT = register("gorilla_hurt");
        MOSQUITO_LOOP = register("mosquito_loop");
        MOSQUITO_HURT = register("mosquito_hurt");
        MOSQUITO_DIE = register("mosquito_die");
        RATTLESNAKE_LOOP = register("rattlesnake_loop");
        RATTLESNAKE_HURT = register("rattlesnake_hurt");
        RATTLESNAKE_ATTACK = register("rattlesnake_attack");
        ENDERGRADE_IDLE = register("endergrade_idle");
        ENDERGRADE_HURT = register("endergrade_hurt");
        LOBSTER_HURT = register("lobster_hurt");
        LOBSTER_ATTACK = register("lobster_attack");
        KOMODO_DRAGON_IDLE = register("komodo_dragon_idle");
        KOMODO_DRAGON_HURT = register("komodo_dragon_hurt");
        SUNBIRD_IDLE = register("sunbird_idle");
        SUNBIRD_HURT = register("sunbird_hurt");
        CAPUCHIN_MONKEY_IDLE = register("capuchin_monkey_idle");
        CAPUCHIN_MONKEY_HURT = register("capuchin_monkey_hurt");
        BONE_SERPENT_IDLE = register("bone_serpent_idle");
        BONE_SERPENT_HURT = register("bone_serpent_hurt");
        CENTIPEDE_WALK = register("centipede_walk");
        CENTIPEDE_HURT = register("centipede_hurt");
        CENTIPEDE_ATTACK = register("centipede_attack");
        WARPED_TOAD_IDLE = register("warped_toad_idle");
        WARPED_TOAD_HURT = register("warped_toad_hurt");
        MOOSE_IDLE = register("moose_idle");
        MOOSE_HURT = register("moose_hurt");
        MOOSE_JOSTLE = register("moose_jostle");
        MIMICUBE_JUMP = register("mimicube_jump");
        MIMICUBE_HURT = register("mimicube_hurt");
        RACCOON_IDLE = register("raccoon_idle");
        RACCOON_HURT = register("raccoon_hurt");
        MARACA = register("maraca");
        LA_CUCARACHA = register("la_cucaracha");
        SEAL_IDLE = register("seal_idle");
        SEAL_HURT = register("seal_hurt");
        COCKROACH_HURT = register("cockroach_hurt");
        SHOEBILL_HURT = register("shoebill_hurt");
        ELEPHANT_IDLE = register("elephant_idle");
        ELEPHANT_HURT = register("elephant_hurt");
        ELEPHANT_DIE = register("elephant_die");
        ELEPHANT_TRUMPET = register("elephant_trumpet");
        ELEPHANT_WALK = register("elephant_walk");
        SOUL_VULTURE_IDLE = register("soul_vulture_idle");
        SOUL_VULTURE_HURT = register("soul_vulture_hurt");
        SNOW_LEOPARD_IDLE = register("snow_leopard_idle");
        SNOW_LEOPARD_HURT = register("snow_leopard_hurt");
        SPECTRE_IDLE = register("spectre_idle");
        SPECTRE_HURT = register("spectre_hurt");
        CROW_IDLE = register("crow_idle");
        CROW_HURT = register("crow_hurt");
        ALLIGATOR_SNAPPING_TURTLE_IDLE = register("alligator_snapping_turtle_idle");
        ALLIGATOR_SNAPPING_TURTLE_HURT = register("alligator_snapping_turtle_hurt");
        MUNGUS_IDLE = register("mungus_idle");
        MUNGUS_HURT = register("mungus_hurt");
        MUNGUS_LASER_END = register("mungus_laser_end");
        MUNGUS_LASER_LOOP = register("mungus_laser_loop");
        MUNGUS_LASER_GROW = register("mungus_laser_grow");
        MANTIS_SHRIMP_SNAP = register("mantis_shrimp_snap");
        MANTIS_SHRIMP_HURT = register("mantis_shrimp_hurt");
        GUSTER_IDLE = register("guster_idle");
        GUSTER_HURT = register("guster_hurt");
        WARPED_MOSCO_IDLE = register("warped_mosco_idle");
        WARPED_MOSCO_HURT = register("warped_mosco_hurt");
        STRADDLER_IDLE = register("straddler_idle");
        STRADDLER_HURT = register("straddler_hurt");
        EMU_IDLE = register("emu_idle");
        EMU_HURT = register("emu_hurt");
        PLATYPUS_IDLE = register("platypus_idle");
        PLATYPUS_HURT = register("platypus_hurt");
        DROPBEAR_IDLE = register("dropbear_idle");
        DROPBEAR_HURT = register("dropbear_hurt");
        TASMANIAN_DEVIL_IDLE = register("tasmanian_devil_idle");
        TASMANIAN_DEVIL_HURT = register("tasmanian_devil_hurt");
        TASMANIAN_DEVIL_ROAR = register("tasmanian_devil_roar");
        KANGAROO_IDLE = register("kangaroo_idle");
        KANGAROO_HURT = register("kangaroo_hurt");
        CACHALOT_WHALE_IDLE = register("cachalot_whale_idle");
        CACHALOT_WHALE_HURT = register("cachalot_whale_hurt");
        CACHALOT_WHALE_CLICK = register("cachalot_whale_click");
        LEAFCUTTER_ANT_HURT = register("leafcutter_ant_hurt");
        LEAFCUTTER_ANT_QUEEN_HURT = register("leafcutter_ant_queen_hurt");
        ENDERIOPHAGE_HURT = register("enderiophage_hurt");
        ENDERIOPHAGE_SQUISH = register("enderiophage_squish");
        ENDERIOPHAGE_WALK = register("enderiophage_walk");
        MUSIC_DISC_THIME = register("music_disc_thime");
        BALD_EAGLE_IDLE = register("bald_eagle_idle");
        BALD_EAGLE_HURT = register("bald_eagle_hurt");
        TIGER_IDLE = register("tiger_idle");
        TIGER_HURT = register("tiger_hurt");
        TIGER_ANGRY = register("tiger_angry");
        TARANTULA_HAWK_WING = register("tarantula_hawk_wing");
        TARANTULA_HAWK_HURT = register("tarantula_hawk_hurt");
        MUSIC_WORMBOSS = register("music_wormboss");
        VOID_WORM_IDLE = register("void_worm_idle");
        VOID_WORM_HURT = register("void_worm_hurt");
        VOID_PORTAL_CLOSE = register("void_portal_close");
        VOID_PORTAL_OPEN = register("void_portal_open");
        MIMIC_OCTOPUS_IDLE = register("mimic_octopus_idle");
        MIMIC_OCTOPUS_HURT = register("mimic_octopus_hurt");
        MUSIC_DISC_DAZE = register("music_disc_daze");
        SEAGULL_IDLE = register("seagull_idle");
        SEAGULL_HURT = register("seagull_hurt");
        FROSTSTALKER_IDLE = register("froststalker_idle");
        FROSTSTALKER_HURT = register("froststalker_hurt");
        TUSKLIN_IDLE = register("tusklin_idle");
        TUSKLIN_HURT = register("tusklin_hurt");
        LAVIATHAN_IDLE = register("laviathan_idle");
        LAVIATHAN_HURT = register("laviathan_hurt");
        COSMAW_IDLE = register("cosmaw_idle");
        COSMAW_HURT = register("cosmaw_hurt");
        TOUCAN_IDLE = register("toucan_idle");
        TOUCAN_HURT = register("toucan_hurt");
        MANED_WOLF_IDLE = register("maned_wolf_idle");
        MANED_WOLF_HURT = register("maned_wolf_hurt");
        ANACONDA_SLITHER = register("anaconda_slither");
        ANACONDA_HURT = register("anaconda_hurt");
        ANACONDA_ATTACK = register("anaconda_attack");
        VINE_LASSO = register("vine_lasso");
        ANTEATER_HURT = register("anteater_hurt");
        ROCKY_ROLLER_IDLE = register("rocky_roller_idle");
        ROCKY_ROLLER_HURT = register("rocky_roller_hurt");
        ROCKY_ROLLER_EARTHQUAKE = register("rocky_roller_earthquake");
        GELADA_MONKEY_IDLE = register("gelada_monkey_idle");
        GELADA_MONKEY_HURT = register("gelada_monkey_hurt");
        FLUTTER_IDLE = register("flutter_idle");
        FLUTTER_HURT = register("flutter_hurt");
        FLUTTER_FLAP = register("flutter_flap");
        FLUTTER_NO = register("flutter_no");
        FLUTTER_YES = register("flutter_yes");
        JERBOA_IDLE = register("jerboa_idle");
        JERBOA_HURT = register("jerboa_hurt");
        TERRAPIN_HURT = register("terrapin_hurt");
        COMB_JELLY_HURT = register("comb_jelly_hurt");
        COSMIC_COD_HURT = register("cosmic_cod_hurt");
        MOSQUITO_CAPSID_CONVERT = register("mosquito_capsid_convert");
        GIANT_SQUID_GAMES = register("giant_squid_games");
        APRIL_FOOLS_SCREAM = register("april_fools_scream");
        APRIL_FOOLS_POWER_OUTAGE = register("april_fools_power_outage");
        APRIL_FOOLS_MUSIC_BOX = register("april_fools_music_box");
        BUNFUNGUS_IDLE = register("bunfungus_idle");
        BUNFUNGUS_HURT = register("bunfungus_hurt");
        BUNFUNGUS_ATTACK = register("bunfungus_attack");
        BUNFUNGUS_JUMP = register("bunfungus_jump");
        BISON_IDLE = register("bison_idle");
        BISON_HURT = register("bison_hurt");
        GIANT_SQUID_HURT = register("giant_squid_hurt");
        GIANT_SQUID_TENTACLE = register("giant_squid_tentacle");
        DEVILS_HOLE_PUPFISH_HURT = register("devils_hole_pupfish_hurt");
        SKELEWAG_HURT = register("skelewag_hurt");
        SKELEWAG_IDLE = register("skelewag_idle");
        RAIN_FROG_HURT = register("rain_frog_hurt");
        RAIN_FROG_IDLE = register("rain_frog_idle");
        POTOO_HURT = register("potoo_hurt");
        POTOO_CALL = register("potoo_call");
        MUDSKIPPER_HURT = register("mudskipper_hurt");
        MUDSKIPPER_WALK = register("mudskipper_walk");
        MUDSKIPPER_SPIT = register("mudskipper_spit");
        RHINOCEROS_IDLE = register("rhinoceros_idle");
        RHINOCEROS_HURT = register("rhinoceros_hurt");
        SUGAR_GLIDER_IDLE = register("sugar_glider_idle");
        SUGAR_GLIDER_HURT = register("sugar_glider_hurt");
        FARSEER_HURT = register("farseer_hurt");
        FARSEER_IDLE = register("farseer_idle");
        FARSEER_EMERGE = register("farseer_emerge");
        FARSEER_BEAM = register("farseer_beam");
        TRANSMUTE_ITEM = register("transmute_item");
        SKREECHER_HURT = register("skreecher_hurt");
        SKREECHER_CALL = register("skreecher_call");
        SKREECHER_DETECT = register("skreecher_detect");
        SKREECHER_CLAP = register("skreecher_clap");
        SCULK_BOOMER = register("sculk_boomer");
        SCULK_BOOMER_FART = register("sculk_boomer_fart");
        UNDERMINER_IDLE = register("underminer_idle");
        UNDERMINER_HURT = register("underminer_hurt");
        UNDERMINER_STEP = register("underminer_step");
        MURMUR_HURT = register("murmur_hurt");
        MURMUR_IDLE = register("murmur_idle");
        MURMUR_NECK = register("murmur_neck");
        MURMUR_ATTACK = register("murmur_attack");
        MURMUR_ANGER = register("murmur_anger");
        TENDON_WHIP = register("tendon_whip");
        SKUNK_HURT = register("skunk_hurt");
        SKUNK_IDLE = register("skunk_idle");
        SKUNK_SPRAY = register("skunk_spray");
        STINK_RAY = register("stink_ray");
        BANANA_SLUG_HURT = register("banana_slug_hurt");
        BANANA_SLUG_SLIME_EXPAND = register("banana_slug_slime_expand");
        BLUE_JAY_IDLE = register("blue_jay_idle");
        BLUE_JAY_HURT = register("blue_jay_hurt");
        BLUE_JAY_SONG = register("blue_jay_song");
        CAIMAN_IDLE = register("caiman_idle");
        CAIMAN_HURT = register("caiman_hurt");
        CAIMAN_SPLASH = register("caiman_splash");
        TRIOPS_HURT = register("triops_hurt");
        END_PIRATE_DOOR = register("end_pirate_door");
    }
}
