package com.github.alexthe666.alexsmobs.client.render;

import com.github.alexthe666.alexsmobs.entity.AMEntityRegistry;
import com.mojang.datafixers.util.Pair;
import net.minecraft.world.entity.EntityType;

import java.util.List;

public class AMMobIcons {

    private static final List<Pair<EntityType, Float>> MOB_ICONS = List.<Pair<EntityType, Float>>of(
            new Pair<>(AMEntityRegistry.GRIZZLY_BEAR, 0.6F),
            new Pair<>(AMEntityRegistry.ROADRUNNER, 0.8F),
            new Pair<>(AMEntityRegistry.BONE_SERPENT, 0.55F),
            new Pair<>(AMEntityRegistry.GAZELLE, 0.6F),
            new Pair<>(AMEntityRegistry.CROCODILE, 0.3F),
            new Pair<>(AMEntityRegistry.FLY, 1.3F),
            new Pair<>(AMEntityRegistry.HUMMINGBIRD, 1.5F),
            new Pair<>(AMEntityRegistry.ORCA, 0.2F),
            new Pair<>(AMEntityRegistry.SUNBIRD, 0.2F),
            new Pair<>(AMEntityRegistry.GORILLA, 0.85F),
            new Pair<>(AMEntityRegistry.CRIMSON_MOSQUITO, 0.6F),
            new Pair<>(AMEntityRegistry.RATTLESNAKE, 0.6F),
            new Pair<>(AMEntityRegistry.ENDERGRADE, 0.8F),
            new Pair<>(AMEntityRegistry.HAMMERHEAD_SHARK, 0.5F),
            new Pair<>(AMEntityRegistry.LOBSTER, 0.85F),
            new Pair<>(AMEntityRegistry.KOMODO_DRAGON, 0.5F),
            new Pair<>(AMEntityRegistry.CAPUCHIN_MONKEY, 0.85F),
            new Pair<>(AMEntityRegistry.CENTIPEDE_HEAD, 0.65F),
            new Pair<>(AMEntityRegistry.WARPED_TOAD, 0.6F),
            new Pair<>(AMEntityRegistry.MOOSE, 0.38F),
            new Pair<>(AMEntityRegistry.MIMICUBE, 0.95F),
            new Pair<>(AMEntityRegistry.RACCOON, 0.8F),
            new Pair<>(AMEntityRegistry.BLOBFISH, 1F),
            new Pair<>(AMEntityRegistry.SEAL, 0.5F),
            new Pair<>(AMEntityRegistry.COCKROACH, 1F),
            new Pair<>(AMEntityRegistry.SHOEBILL, 0.8F),
            new Pair<>(AMEntityRegistry.ELEPHANT, 0.3F),
            new Pair<>(AMEntityRegistry.SOUL_VULTURE, 0.8F),
            new Pair<>(AMEntityRegistry.SNOW_LEOPARD, 0.7F),
            new Pair<>(AMEntityRegistry.SPECTRE, 0.3F),
            new Pair<>(AMEntityRegistry.CROW, 1.3F),
            new Pair<>(AMEntityRegistry.ALLIGATOR_SNAPPING_TURTLE, 0.65F),
            new Pair<>(AMEntityRegistry.MUNGUS, 0.7F),
            new Pair<>(AMEntityRegistry.MANTIS_SHRIMP, 0.7F),
            new Pair<>(AMEntityRegistry.GUSTER, 0.55F),
            new Pair<>(AMEntityRegistry.WARPED_MOSCO, 0.35F),
            new Pair<>(AMEntityRegistry.STRADDLER, 0.38F),
            new Pair<>(AMEntityRegistry.STRADPOLE, 0.9F),
            new Pair<>(AMEntityRegistry.EMU, 0.7F),
            new Pair<>(AMEntityRegistry.PLATYPUS, 1F),
            new Pair<>(AMEntityRegistry.DROPBEAR, 0.65F),
            new Pair<>(AMEntityRegistry.TASMANIAN_DEVIL, 1.2F),
            new Pair<>(AMEntityRegistry.KANGAROO, 0.7F),
            new Pair<>(AMEntityRegistry.CACHALOT_WHALE, 0.1F),
            new Pair<>(AMEntityRegistry.LEAFCUTTER_ANT, 1.2F),
            new Pair<>(AMEntityRegistry.ENDERIOPHAGE, 0.65F),
            new Pair<>(AMEntityRegistry.BALD_EAGLE, 0.85F),
            new Pair<>(AMEntityRegistry.TIGER, 0.65F),
            new Pair<>(AMEntityRegistry.TARANTULA_HAWK, 0.7F),
            new Pair<>(AMEntityRegistry.VOID_WORM, 0.3F),
            new Pair<>(AMEntityRegistry.FRILLED_SHARK, 0.65F),
            new Pair<>(AMEntityRegistry.MIMIC_OCTOPUS, 0.7F),
            new Pair<>(AMEntityRegistry.SEAGULL, 1.2F),
            new Pair<>(AMEntityRegistry.FROSTSTALKER, 0.8F),
            new Pair<>(AMEntityRegistry.TUSKLIN, 0.6F),
            new Pair<>(AMEntityRegistry.LAVIATHAN, 0.2F),
            new Pair<>(AMEntityRegistry.COSMAW, 0.32F),
            new Pair<>(AMEntityRegistry.TOUCAN, 1.3F),
            new Pair<>(AMEntityRegistry.MANED_WOLF, 0.85F),
            new Pair<>(AMEntityRegistry.ANACONDA, 1.0F),
            new Pair<>(AMEntityRegistry.ANTEATER, 0.5F),
            new Pair<>(AMEntityRegistry.ROCKY_ROLLER, 0.65F),
            new Pair<>(AMEntityRegistry.FLUTTER, 1.15F),
            new Pair<>(AMEntityRegistry.GELADA_MONKEY, 0.65F),
            new Pair<>(AMEntityRegistry.JERBOA, 1.3F),
            new Pair<>(AMEntityRegistry.TERRAPIN, 1.1F),
            new Pair<>(AMEntityRegistry.COMB_JELLY, 1.0F),
            new Pair<>(AMEntityRegistry.COSMIC_COD, 1.3F),
            new Pair<>(AMEntityRegistry.BUNFUNGUS, 0.5F),
            new Pair<>(AMEntityRegistry.BISON, 0.45F),
            new Pair<>(AMEntityRegistry.GIANT_SQUID, 0.3F),
            new Pair<>(AMEntityRegistry.DEVILS_HOLE_PUPFISH, 1.4F),
            new Pair<>(AMEntityRegistry.CATFISH, 1.15F),
            new Pair<>(AMEntityRegistry.FLYING_FISH, 1.2F),
            new Pair<>(AMEntityRegistry.SKELEWAG, 0.5F),
            new Pair<>(AMEntityRegistry.RAIN_FROG, 1.8F),
            new Pair<>(AMEntityRegistry.POTOO, 1.2F),
            new Pair<>(AMEntityRegistry.MUDSKIPPER, 1.2F),
            new Pair<>(AMEntityRegistry.RHINOCEROS, 0.4F),
            new Pair<>(AMEntityRegistry.SUGAR_GLIDER, 1.3F),
            new Pair<>(AMEntityRegistry.FARSEER, 0.6F),
            new Pair<>(AMEntityRegistry.SKREECHER, 0.77F),
            new Pair<>(AMEntityRegistry.UNDERMINER, 0.65F),
            new Pair<>(AMEntityRegistry.MURMUR, 0.65F),
            new Pair<>(AMEntityRegistry.SKUNK, 1F),
            new Pair<>(AMEntityRegistry.BANANA_SLUG, 1.5F),
            new Pair<>(AMEntityRegistry.BLUE_JAY, 1.4F),
            new Pair<>(AMEntityRegistry.CAIMAN, 0.5F),
            new Pair<>(AMEntityRegistry.TRIOPS, 0.95F)
    );

    public static List<Pair<EntityType, Float>> getMobIcons() {
        return MOB_ICONS;
    }


}
