package com.github.alexthe666.alexsmobs.config;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;

/** Fabric: POJO holding config values (same defaults as Forge builder). Loaded by ConfigHolder and baked into AMConfig. */
public class CommonConfig {

    public final double lavaOpacity;
    public final boolean shadersCompat;
    public final boolean neutralBoneSerpents;
    public final boolean lavaBottleEnabled;
    public final boolean spidersAttackFlies;
    public final boolean wolvesAttackMoose;
    public final boolean polarBearsAttackSeals;
    public final boolean catsAndFoxesAttackJerboas;
    public final boolean dolphinsAttackFlyingFish;
    public final boolean bananasDropFromLeaves;
    public final int bananaChance;
    public final int grizzlyBearSpawnWeight;
    public final int grizzlyBearSpawnRolls;
    public final int roadrunnerSpawnWeight;
    public final int roadrunnerSpawnRolls;
    public final int boneSerpentSpawnWeight;
    public final int boneSeprentSpawnRolls;
    public final int gazelleSpawnWeight;
    public final int gazelleSpawnRolls;
    public final int crocodileSpawnWeight;
    public final int crocSpawnRolls;
    public final int flySpawnWeight;
    public final int flySpawnRolls;
    public final int hummingbirdSpawnWeight;
    public final int hummingbirdSpawnRolls;
    public final int orcaSpawnWeight;
    public final int orcaSpawnRolls;
    public final int sunbirdSpawnWeight;
    public final int sunbirdSpawnRolls;
    public final int gorillaSpawnWeight;
    public final int gorillaSpawnRolls;
    public final int crimsonMosquitoSpawnWeight;
    public final int crimsonMosquitoSpawnRolls;
    public final int rattlesnakeSpawnWeight;
    public final int rattlesnakeSpawnRolls;
    public final int endergradeSpawnWeight;
    public final int endergradeSpawnRolls;
    public final int hammerheadSharkSpawnWeight;
    public final int hammerheadSharkSpawnRolls;
    public final int lobsterSpawnWeight;
    public final int lobsterSpawnRolls;
    public final int komodoDragonSpawnWeight;
    public final int komodoDragonSpawnRolls;
    public final int capuchinMonkeySpawnWeight;
    public final int capuchinMonkeySpawnRolls;
    public final int caveCentipedeSpawnWeight;
    public final int caveCentipedeSpawnRolls;
    public final int caveCentipedeSpawnHeight;
    public final int warpedToadSpawnWeight;
    public final int warpedToadSpawnRolls;
    public final int mooseSpawnWeight;
    public final int mooseSpawnRolls;
    public final int mimicubeSpawnWeight;
    public final int mimicubeSpawnRolls;
    public final int raccoonSpawnWeight;
    public final int raccoonSpawnRolls;
    public final int blobfishSpawnWeight;
    public final int blobfishSpawnRolls;
    public final int blobfishSpawnHeight;
    public final int sealSpawnWeight;
    public final int sealSpawnRolls;
    public final int cockroachSpawnWeight;
    public final int cockroachSpawnRolls;
    public final int shoebillSpawnWeight;
    public final int shoebillSpawnRolls;
    public final int elephantSpawnWeight;
    public final int elephantSpawnRolls;
    public final int soulVultureSpawnWeight;
    public final int soulVultureSpawnRolls;
    public final int snowLeopardSpawnWeight;
    public final int snowLeopardSpawnRolls;
    public final int spectreSpawnWeight;
    public final int spectreSpawnRolls;
    public final int crowSpawnWeight;
    public final int crowSpawnRolls;
    public final int alligatorSnappingTurtleSpawnWeight;
    public final int alligatorSnappingTurtleSpawnRolls;
    public final int mungusSpawnWeight;
    public final int mungusSpawnRolls;
    public final int mantisShrimpSpawnWeight;
    public final int mantisShrimpSpawnRolls;
    public final int gusterSpawnWeight;
    public final int gusterSpawnRolls;
    public final int warpedMoscoSpawnWeight;
    public final int warpedMoscoSpawnRolls;
    public final int straddlerSpawnWeight;
    public final int straddlerSpawnRolls;
    public final int stradpoleSpawnWeight;
    public final int stradpoleSpawnRolls;
    public final int emuSpawnWeight;
    public final int emuSpawnRolls;
    public final int platypusSpawnWeight;
    public final int platypusSpawnRolls;
    public final int dropbearSpawnWeight;
    public final int dropbearSpawnRolls;
    public final int tasmanianDevilSpawnWeight;
    public final int tasmanianDevilSpawnRolls;
    public final int kangarooSpawnWeight;
    public final int kangarooSpawnRolls;
    public final int cachalotWhaleSpawnWeight;
    public final int cachalotWhaleSpawnRolls;
    public final int enderiophageSpawnWeight;
    public final int enderiophageSpawnRolls;
    public final int baldEagleSpawnWeight;
    public final int baldEagleSpawnRolls;
    public final int tigerSpawnWeight;
    public final int tigerSpawnRolls;
    public final int tarantulaHawkSpawnWeight;
    public final int tarantulaHawkSpawnRolls;
    public final int voidWormSpawnWeight;
    public final int voidWormSpawnRolls;
    public final int frilledSharkSpawnWeight;
    public final int frilledSharkSpawnRolls;
    public final int mimicOctopusSpawnWeight;
    public final int mimicOctopusSpawnRolls;
    public final int seagullSpawnWeight;
    public final int seagullSpawnRolls;
    public final int froststalkerSpawnWeight;
    public final int froststalkerSpawnRolls;
    public final int tusklinSpawnWeight;
    public final int tusklinSpawnRolls;
    public final int laviathanSpawnWeight;
    public final int laviathanSpawnRolls;
    public final int cosmawSpawnWeight;
    public final int cosmawSpawnRolls;
    public final int toucanSpawnWeight;
    public final int toucanSpawnRolls;
    public final int manedWolfSpawnWeight;
    public final int manedWolfSpawnRolls;
    public final int anacondaSpawnWeight;
    public final int anacondaSpawnRolls;
    public final int anteaterSpawnWeight;
    public final int anteaterSpawnRolls;
    public final int rockyRollerSpawnWeight;
    public final int rockyRollerSpawnRolls;
    public final int flutterSpawnWeight;
    public final int flutterSpawnRolls;
    public final int geladaMonkeySpawnWeight;
    public final int geladaMonkeySpawnRolls;
    public final int geladaMonkeySpawnHeight;
    public final int jerboaSpawnRolls;
    public final int jerboaSpawnWeight;
    public final int terrapinSpawnRolls;
    public final int terrapinSpawnWeight;
    public final int combJellySpawnRolls;
    public final int combJellySpawnWeight;
    public final int cosmicCodSpawnRolls;
    public final int cosmicCodSpawnWeight;
    public final int bunfungusSpawnWeight;
    public final int bunfungusSpawnRolls;
    public final int bisonSpawnWeight;
    public final int bisonSpawnRolls;
    public final int giantSquidSpawnWeight;
    public final int giantSquidSpawnRolls;
    public final int devilsHolePupfishSpawnWeight;
    public final int devilsHolePupfishSpawnRolls;
    public final int catfishSpawnWeight;
    public final int catfishSpawnRolls;
    public final int flyingFishSpawnWeight;
    public final int flyingFishSpawnRolls;
    public final int skelewagSpawnWeight;
    public final int skelewagSpawnRolls;
    public final int rainFrogSpawnWeight;
    public final int rainFrogSpawnRolls;
    public final int potooSpawnWeight;
    public final int potooSpawnRolls;
    public final int mudskipperSpawnWeight;
    public final int mudskipperSpawnRolls;
    public final int rhinocerosSpawnWeight;
    public final int rhinocerosSpawnRolls;
    public final int sugarGliderSpawnWeight;
    public final int sugarGliderSpawnRolls;
    public final int farseerSpawnWeight;
    public final int farseerSpawnRolls;
    public final int skreecherSpawnWeight;
    public final int skreecherSpawnRolls;
    public final int underminerSpawnWeight;
    public final int underminerSpawnRolls;
    public final int murmurSpawnWeight;
    public final int murmurSpawnRolls;
    public final int murmurSpawnHeight;
    public final int skunkSpawnWeight;
    public final int skunkSpawnRolls;
    public final int bananaSlugSpawnWeight;
    public final int bananaSlugSpawnRolls;
    public final int blueJaySpawnWeight;
    public final int blueJaySpawnRolls;
   public final int caimanSpawnWeight;
    public final int caimanSpawnRolls;
    public final int triopsSpawnWeight;
    public final int triopsSpawnRolls;
    public final boolean giveBookOnStartup;
    public final boolean mimicubeSpawnInEndCity;
    public final boolean mimicreamRepair;
    public final List<String> mimicreamBlacklist;
    public final boolean raccoonStealFromChests;
    public final boolean crowsStealCrops;
    public final boolean fishOilMeme;
    public final boolean soulVultureSpawnOnFossil;
    public final boolean acaciaBlossomsDropFromLeaves;
    public final int acaciaBlossomChance;
    public final boolean wanderingTraderOffers;
    public final int mungusBiomeTransformationType;
    public final List<String> mungusBiomeMatches;
    public boolean limitGusterSpawnsToWeather;
    public boolean warpedMoscoTransformation;
    public final List<String> warpedMoscoMobTriggers;
    public final boolean straddleboardEnchants;
    public final boolean emuTargetSkeletons;
    public final double emuPantsDodgeChance;
    public final double leafcutterAntFungusGrowChance;
    public final int leafcutterAntRepopulateFeedings;
    public final int leafcutterAntColonySize;
    public final double leafcutterAntBreakLeavesChance;
    public final boolean beachedCachalotWhales;
    public final boolean cachalotDestruction;
    public final double cachalotVolume;
    public final int beachedCachalotWhaleSpawnChance;
    public final int beachedCachalotWhaleSpawnDelay;
    public final double leafcutterAnthillSpawnChance;
    public final boolean falconryTeleportsBack;
    public final boolean fireproofTarantulaHawk;
    public final boolean voidWormSummonable;
    public final List<String> voidWormSpawnDimensions;
    public final double voidWormDamageModifier;
    public final double voidWormMaxHealth;
    public final boolean seagullStealing;
    public final List<String> seagullStealingBlacklist;
    public final boolean clingingFlipEffect;
    public final double tusklinShoesBarteringChance;
    public final double rainbowGlassFidelity;
    public boolean bunfungusTransformation;
    public boolean restrictPupfishSpawns;
    public int pupfishChunkSpawnDistance;
    public boolean restrictSkelewagSpawns;
    public boolean restrictFarseerSpawns;
    public boolean restrictUnderminerSpawns;
    public int farseerBorderSpawnDistance;
    public boolean superSecretSettings;
    public boolean addLootToChests;
    public final List<String> transmutationBlacklist;
    public boolean limitTransmutingToLootTables;
    public boolean transmutingTableExplodes;
    public int transmutingExperienceCost;
    public double transmutingWeightAddStep;
    public double transmutingWeightRemoveStep;
    public double underminerDisappearDistance;
    public final boolean skreechersSummonWarden;
    public int pathfindingThreads;

    public CommonConfig() {
        giveBookOnStartup = true;
        lavaOpacity = 0.65D;
        shadersCompat = false;
        bananasDropFromLeaves = true;
        bananaChance = 200;
        spidersAttackFlies = true;
        wolvesAttackMoose = true;
        polarBearsAttackSeals = true;
        catsAndFoxesAttackJerboas = true;
        dolphinsAttackFlyingFish = true;
        lavaBottleEnabled = true;
        neutralBoneSerpents = false;
        mimicubeSpawnInEndCity = true;
        mimicreamRepair = true;
        mimicreamBlacklist = Lists.newArrayList("alexsmobs:blood_sprayer", "alexsmobs:hemolymph_blaster");
        raccoonStealFromChests = true;
        crowsStealCrops = true;
        fishOilMeme = true;
        soulVultureSpawnOnFossil = true;
        acaciaBlossomsDropFromLeaves = true;
        acaciaBlossomChance = 130;
        wanderingTraderOffers = true;
        mungusBiomeTransformationType = 2;
        mungusBiomeMatches = Lists.newArrayList(
            "minecraft:red_mushroom|minecraft:mushroom_fields|minecraft:mycelium",
            "minecraft:brown_mushroom|minecraft:mushroom_fields|minecraft:mycelium",
            "minecraft:crimson_fungus|minecraft:crimson_forest|minecraft:crimson_nylium",
            "minecraft:warped_fungus|minecraft:warped_forest|minecraft:warped_nylium");
        limitGusterSpawnsToWeather = true;
        warpedMoscoTransformation = true;
        warpedMoscoMobTriggers = Lists.newArrayList("");
        straddleboardEnchants = true;
        emuTargetSkeletons = true;
        emuPantsDodgeChance = 0.45D;
        cachalotDestruction = true;
        cachalotVolume = 3D;
        leafcutterAntFungusGrowChance = 0.3D;
        leafcutterAntRepopulateFeedings = 25;
        leafcutterAntColonySize = 10;
        leafcutterAntBreakLeavesChance = 0.2D;
        falconryTeleportsBack = false;
        fireproofTarantulaHawk = false;
        voidWormSpawnDimensions = Lists.newArrayList("minecraft:the_end");
        voidWormDamageModifier = 1.0D;
        voidWormMaxHealth = 160.0D;
        voidWormSummonable = true;
        seagullStealing = true;
        seagullStealingBlacklist = new ArrayList<>();
        clingingFlipEffect = false;
        tusklinShoesBarteringChance = 0.025;
        rainbowGlassFidelity = 16.0;
        bunfungusTransformation = true;
        addLootToChests = true;
        transmutationBlacklist = Lists.newArrayList("minecraft:beacon");
        limitTransmutingToLootTables = false;
        transmutingTableExplodes = true;
        transmutingExperienceCost = 3;
        transmutingWeightAddStep = 3.0;
        transmutingWeightRemoveStep = 4.0;
        skreechersSummonWarden = true;
        underminerDisappearDistance = 8.0;
        // spawning (same defaults as AMConfig)
        grizzlyBearSpawnWeight = AMConfig.grizzlyBearSpawnWeight;
        grizzlyBearSpawnRolls = AMConfig.grizzlyBearSpawnRolls;
        roadrunnerSpawnWeight = AMConfig.roadrunnerSpawnWeight;
        roadrunnerSpawnRolls = AMConfig.roadrunnerSpawnRolls;
        boneSerpentSpawnWeight = AMConfig.boneSerpentSpawnWeight;
        boneSeprentSpawnRolls = AMConfig.boneSeprentSpawnRolls;
        gazelleSpawnWeight = AMConfig.gazelleSpawnWeight;
        gazelleSpawnRolls = AMConfig.gazelleSpawnRolls;
        crocodileSpawnWeight = AMConfig.crocodileSpawnWeight;
        crocSpawnRolls = AMConfig.crocSpawnRolls;
        flySpawnWeight = AMConfig.flySpawnWeight;
        flySpawnRolls = AMConfig.flySpawnRolls;
        hummingbirdSpawnWeight = AMConfig.hummingbirdSpawnWeight;
        hummingbirdSpawnRolls = AMConfig.flySpawnRolls;
        orcaSpawnWeight = AMConfig.orcaSpawnWeight;
        orcaSpawnRolls = AMConfig.orcaSpawnRolls;
        sunbirdSpawnWeight = AMConfig.sunbirdSpawnWeight;
        sunbirdSpawnRolls = AMConfig.sunbirdSpawnRolls;
        gorillaSpawnWeight = AMConfig.gorillaSpawnWeight;
        gorillaSpawnRolls = AMConfig.gorillaSpawnRolls;
        crimsonMosquitoSpawnWeight = AMConfig.crimsonMosquitoSpawnWeight;
        crimsonMosquitoSpawnRolls = AMConfig.crimsonMosquitoSpawnRolls;
        rattlesnakeSpawnWeight = AMConfig.rattlesnakeSpawnWeight;
        rattlesnakeSpawnRolls = AMConfig.rattlesnakeSpawnRolls;
        endergradeSpawnWeight = AMConfig.endergradeSpawnWeight;
        endergradeSpawnRolls = AMConfig.endergradeSpawnRolls;
        hammerheadSharkSpawnWeight = AMConfig.hammerheadSharkSpawnWeight;
        hammerheadSharkSpawnRolls = AMConfig.hammerheadSharkSpawnRolls;
        lobsterSpawnWeight = AMConfig.lobsterSpawnWeight;
        lobsterSpawnRolls = AMConfig.lobsterSpawnRolls;
        komodoDragonSpawnWeight = AMConfig.komodoDragonSpawnWeight;
        komodoDragonSpawnRolls = AMConfig.komodoDragonSpawnRolls;
        capuchinMonkeySpawnWeight = AMConfig.capuchinMonkeySpawnWeight;
        capuchinMonkeySpawnRolls = AMConfig.capuchinMonkeySpawnRolls;
        caveCentipedeSpawnWeight = AMConfig.caveCentipedeSpawnWeight;
        caveCentipedeSpawnRolls = AMConfig.caveCentipedeSpawnRolls;
        warpedToadSpawnWeight = AMConfig.warpedToadSpawnWeight;
        warpedToadSpawnRolls = AMConfig.warpedToadSpawnRolls;
        mooseSpawnWeight = AMConfig.mooseSpawnWeight;
        mooseSpawnRolls = AMConfig.mooseSpawnRolls;
        mimicubeSpawnWeight = AMConfig.mimicubeSpawnWeight;
        mimicubeSpawnRolls = AMConfig.mimicubeSpawnRolls;
        raccoonSpawnWeight = AMConfig.raccoonSpawnWeight;
        raccoonSpawnRolls = AMConfig.raccoonSpawnRolls;
        blobfishSpawnWeight = AMConfig.blobfishSpawnWeight;
        blobfishSpawnRolls = AMConfig.blobfishSpawnRolls;
        sealSpawnWeight = AMConfig.sealSpawnWeight;
        sealSpawnRolls = AMConfig.sealSpawnRolls;
        cockroachSpawnWeight = AMConfig.cockroachSpawnWeight;
        cockroachSpawnRolls = AMConfig.cockroachSpawnRolls;
        shoebillSpawnWeight = AMConfig.shoebillSpawnWeight;
        shoebillSpawnRolls = AMConfig.shoebillSpawnRolls;
        elephantSpawnWeight = AMConfig.elephantSpawnWeight;
        elephantSpawnRolls = AMConfig.elephantSpawnRolls;
        soulVultureSpawnWeight = AMConfig.soulVultureSpawnWeight;
        soulVultureSpawnRolls = AMConfig.soulVultureSpawnRolls;
        snowLeopardSpawnWeight = AMConfig.snowLeopardSpawnWeight;
        snowLeopardSpawnRolls = AMConfig.snowLeopardSpawnRolls;
        spectreSpawnWeight = AMConfig.spectreSpawnWeight;
        spectreSpawnRolls = AMConfig.spectreSpawnRolls;
        crowSpawnWeight = AMConfig.crowSpawnWeight;
        crowSpawnRolls = AMConfig.crowSpawnRolls;
        alligatorSnappingTurtleSpawnWeight = AMConfig.alligatorSnappingTurtleSpawnWeight;
        alligatorSnappingTurtleSpawnRolls = AMConfig.alligatorSnappingTurtleSpawnRolls;
        mungusSpawnWeight = AMConfig.mungusSpawnWeight;
        mungusSpawnRolls = AMConfig.mungusSpawnRolls;
        mantisShrimpSpawnWeight = AMConfig.mantisShrimpSpawnWeight;
        mantisShrimpSpawnRolls = AMConfig.mantisShrimpSpawnRolls;
        gusterSpawnWeight = AMConfig.gusterSpawnWeight;
        gusterSpawnRolls = AMConfig.gusterSpawnRolls;
        warpedMoscoSpawnWeight = AMConfig.warpedMoscoSpawnWeight;
        warpedMoscoSpawnRolls = AMConfig.warpedMoscoSpawnRolls;
        straddlerSpawnWeight = AMConfig.straddlerSpawnWeight;
        straddlerSpawnRolls = AMConfig.straddlerSpawnRolls;
        stradpoleSpawnWeight = AMConfig.stradpoleSpawnWeight;
        stradpoleSpawnRolls = AMConfig.stradpoleSpawnRolls;
        emuSpawnWeight = AMConfig.emuSpawnWeight;
        emuSpawnRolls = AMConfig.emuSpawnRolls;
        platypusSpawnWeight = AMConfig.platypusSpawnWeight;
        platypusSpawnRolls = AMConfig.platypusSpawnRolls;
        dropbearSpawnWeight = AMConfig.dropbearSpawnWeight;
        dropbearSpawnRolls = AMConfig.dropbearSpawnRolls;
        tasmanianDevilSpawnWeight = AMConfig.tasmanianDevilSpawnWeight;
        tasmanianDevilSpawnRolls = AMConfig.tasmanianDevilSpawnRolls;
        kangarooSpawnWeight = AMConfig.kangarooSpawnWeight;
        kangarooSpawnRolls = AMConfig.kangarooSpawnRolls;
        cachalotWhaleSpawnWeight = AMConfig.cachalotWhaleSpawnWeight;
        cachalotWhaleSpawnRolls = AMConfig.cachalotWhaleSpawnRolls;
        enderiophageSpawnWeight = AMConfig.enderiophageSpawnWeight;
        enderiophageSpawnRolls = AMConfig.enderiophageSpawnRolls;
        baldEagleSpawnWeight = AMConfig.baldEagleSpawnWeight;
        baldEagleSpawnRolls = AMConfig.baldEagleSpawnRolls;
        tigerSpawnWeight = AMConfig.tigerSpawnWeight;
        tigerSpawnRolls = AMConfig.tigerSpawnRolls;
        tarantulaHawkSpawnWeight = AMConfig.tarantulaHawkSpawnWeight;
        tarantulaHawkSpawnRolls = AMConfig.tarantulaHawkSpawnRolls;
        voidWormSpawnWeight = AMConfig.voidWormSpawnWeight;
        voidWormSpawnRolls = AMConfig.voidWormSpawnRolls;
        frilledSharkSpawnWeight = AMConfig.frilledSharkSpawnWeight;
        frilledSharkSpawnRolls = AMConfig.frilledSharkSpawnRolls;
        mimicOctopusSpawnWeight = AMConfig.mimicOctopusSpawnWeight;
        mimicOctopusSpawnRolls = AMConfig.mimicOctopusSpawnRolls;
        seagullSpawnWeight = AMConfig.seagullSpawnWeight;
        seagullSpawnRolls = AMConfig.seagullSpawnRolls;
        froststalkerSpawnWeight = AMConfig.froststalkerSpawnWeight;
        froststalkerSpawnRolls = AMConfig.froststalkerSpawnRolls;
        tusklinSpawnWeight = AMConfig.tusklinSpawnWeight;
        tusklinSpawnRolls = AMConfig.tusklinSpawnRolls;
        laviathanSpawnWeight = AMConfig.laviathanSpawnWeight;
        laviathanSpawnRolls = AMConfig.laviathanSpawnRolls;
        cosmawSpawnWeight = AMConfig.cosmawSpawnWeight;
        cosmawSpawnRolls = AMConfig.cosmawSpawnRolls;
        toucanSpawnWeight = AMConfig.toucanSpawnWeight;
        toucanSpawnRolls = AMConfig.toucanSpawnRolls;
        manedWolfSpawnWeight = AMConfig.manedWolfSpawnWeight;
        manedWolfSpawnRolls = AMConfig.manedWolfSpawnRolls;
        anacondaSpawnWeight = AMConfig.anacondaSpawnWeight;
        anacondaSpawnRolls = AMConfig.anacondaSpawnRolls;
        anteaterSpawnWeight = AMConfig.anteaterSpawnWeight;
        anteaterSpawnRolls = AMConfig.anteaterSpawnRolls;
        rockyRollerSpawnWeight = AMConfig.rockyRollerSpawnWeight;
        rockyRollerSpawnRolls = AMConfig.rockyRollerSpawnRolls;
        flutterSpawnWeight = AMConfig.flutterSpawnWeight;
        flutterSpawnRolls = AMConfig.flutterSpawnRolls;
        geladaMonkeySpawnWeight = AMConfig.geladaMonkeySpawnWeight;
        geladaMonkeySpawnRolls = AMConfig.geladaMonkeySpawnRolls;
        jerboaSpawnWeight = AMConfig.jerboaSpawnWeight;
        jerboaSpawnRolls = AMConfig.jerboaSpawnRolls;
        terrapinSpawnWeight = AMConfig.terrapinSpawnWeight;
        terrapinSpawnRolls = AMConfig.terrapinSpawnRolls;
        combJellySpawnWeight = AMConfig.combJellySpawnWeight;
        combJellySpawnRolls = AMConfig.combJellySpawnRolls;
        cosmicCodSpawnWeight = AMConfig.cosmicCodSpawnWeight;
        cosmicCodSpawnRolls = AMConfig.cosmicCodSpawnRolls;
        bunfungusSpawnWeight = AMConfig.bunfungusSpawnWeight;
        bunfungusSpawnRolls = AMConfig.bunfungusSpawnRolls;
        bisonSpawnWeight = AMConfig.bisonSpawnWeight;
        bisonSpawnRolls = AMConfig.bisonSpawnRolls;
        giantSquidSpawnWeight = AMConfig.giantSquidSpawnWeight;
        giantSquidSpawnRolls = AMConfig.giantSquidSpawnRolls;
        devilsHolePupfishSpawnWeight = AMConfig.devilsHolePupfishSpawnWeight;
        devilsHolePupfishSpawnRolls = AMConfig.devilsHolePupfishSpawnRolls;
        catfishSpawnWeight = AMConfig.catfishSpawnWeight;
        catfishSpawnRolls = AMConfig.catfishSpawnRolls;
        flyingFishSpawnWeight = AMConfig.flyingFishSpawnWeight;
        flyingFishSpawnRolls = AMConfig.flyingFishSpawnRolls;
        skelewagSpawnWeight = AMConfig.skelewagSpawnWeight;
        skelewagSpawnRolls = AMConfig.skelewagSpawnRolls;
        rainFrogSpawnWeight = AMConfig.rainFrogSpawnWeight;
        rainFrogSpawnRolls = AMConfig.rainFrogSpawnRolls;
        potooSpawnWeight = AMConfig.potooSpawnWeight;
        potooSpawnRolls = AMConfig.potooSpawnRolls;
        mudskipperSpawnWeight = AMConfig.mudskipperSpawnWeight;
        mudskipperSpawnRolls = AMConfig.mudskipperSpawnRolls;
        rhinocerosSpawnWeight = AMConfig.rhinocerosSpawnWeight;
        rhinocerosSpawnRolls = AMConfig.rhinocerosSpawnRolls;
        sugarGliderSpawnWeight = AMConfig.sugarGliderSpawnWeight;
        sugarGliderSpawnRolls = AMConfig.sugarGliderSpawnRolls;
        farseerSpawnWeight = AMConfig.farseerSpawnWeight;
        farseerSpawnRolls = AMConfig.farseerSpawnRolls;
        skreecherSpawnWeight = AMConfig.skreecherSpawnWeight;
        skreecherSpawnRolls = AMConfig.skreecherSpawnRolls;
        underminerSpawnWeight = AMConfig.underminerSpawnWeight;
        underminerSpawnRolls = AMConfig.underminerSpawnRolls;
        murmurSpawnWeight = AMConfig.murmurSpawnWeight;
        murmurSpawnRolls = AMConfig.murmurSpawnRolls;
        skunkSpawnWeight = AMConfig.skunkSpawnWeight;
        skunkSpawnRolls = AMConfig.skunkSpawnRolls;
        bananaSlugSpawnWeight = AMConfig.bananaSlugSpawnWeight;
        bananaSlugSpawnRolls = AMConfig.bananaSlugSpawnRolls;
        blueJaySpawnWeight = AMConfig.blueJaySpawnWeight;
        blueJaySpawnRolls = AMConfig.blueJaySpawnRolls;
        caimanSpawnWeight = AMConfig.caimanSpawnWeight;
        caimanSpawnRolls = AMConfig.caimanSpawnRolls;
        triopsSpawnWeight = AMConfig.triopsSpawnWeight;
        triopsSpawnRolls = AMConfig.triopsSpawnRolls;
        caveCentipedeSpawnHeight = AMConfig.caveCentipedeSpawnHeight;
        blobfishSpawnHeight = AMConfig.blobfishSpawnHeight;
        beachedCachalotWhales = true;
        beachedCachalotWhaleSpawnChance = AMConfig.beachedCachalotWhaleSpawnChance;
        beachedCachalotWhaleSpawnDelay = AMConfig.beachedCachalotWhaleSpawnDelay;
        leafcutterAnthillSpawnChance = AMConfig.leafcutterAnthillSpawnChance;
        geladaMonkeySpawnHeight = AMConfig.geladaMonkeySpawnRolls;
        restrictPupfishSpawns = true;
        pupfishChunkSpawnDistance = AMConfig.pupfishChunkSpawnDistance;
        restrictSkelewagSpawns = true;
        restrictFarseerSpawns = true;
        restrictUnderminerSpawns = true;
        farseerBorderSpawnDistance = AMConfig.farseerBorderSpawnDistance;
        murmurSpawnHeight = AMConfig.murmurSpawnHeight;
        superSecretSettings = false;
        pathfindingThreads = AMConfig.pathfindingThreads;
    }
}
